#!/bin/sh

usage() {
    echo "$0 debug|release"
}

case $1 in
"debug" | "release") ;;
*)
    usage
    exit 1
esac

cmake -E make_directory build &&
cmake -E chdir build cmake --preset=CMakePresets.json --preset="lin-64-$1" ..